### ISSUE TITLE
Reference class not accessible anymore

### ISSUE THREAD

**Issue by spironato** [petitparser/dart-petitparser#102]
We are building a Domain-Specific Language(let call for simplicity xDSL) for our product.
We needed to handle different xDSL versions so in a new xDSL version can be added new grammar or existing grammar can be deprecated. We need to be able to parse different versions of our xDSL and provide errors if f.ex new grammar has been added parsing a source code meant for a older version.
We implemented this with dart-petitparser 2.4.0.
Not sure if is the best approach but we solve the xDSL versioning extending GrammarDefinition adding a new **RefVersion** on top of the existing **Ref**.
**RefVersion** return as the **Ref** a **Reference**.
Now after updating to the version 3.1.0 (we are preparing to move to the null safety version) the **Reference** class is not accessible anymore as was with 2.4.0:

`import 'package:petitparser/src/core/definition/reference.dart';`

Any advice hint best approach how this could be solved with the 3.1.0?

Thanks in advance for the help!

**Comment by renggli** [comment]
AFAIK, the `Reference` class is package private and was never an externally exposed: https://dart-lang.github.io/linter/lints/implementation_imports.html

That said, it has moved to:

```dart
import 'package:petitparser/src/definition/reference.dart';
```

**Comment by spironato** [comment]
Thanks for the message @renggli.
Yep checked in 2.4.0 and just realised that was not exposed.
I did not noticed before and no idea why i could access it before.

Now with the new 3.1.0 i can access it even `petitparser/src/definition/reference.dart`.

**Comment by renggli** [comment]
Are you sure you have the correct import statement? I can import it, I get an appropriate linter warning that I should not import package private files, but it works for me.

Yes, I would prefer not to expose it externally. It is an internal implementation detail. At some point, we might be able to get rid of it with [code generation](https://github.com/dart-lang/language/issues/1507).

I do not understand why you needed to create your own `Reference` implementation. Maybe you can elaborate a bit and post a minimal example?

**Comment by spironato** [comment]
Anyway thanks to your input @renggli this make clear a missing lint rule in our side and we need to change our implementation we can't use private implementation.

**Comment by renggli** [comment]
The built in `Reference` parser can be parametrized:

```dart 
    Parser start() => ref(other, Version.v1);

    Parser other(Version version) {
      switch (version) {
        case v1:
           return ...;
        case v2:
           return ...;
      }
    }
```

Not sure if this is what you are trying to do, or something else?

**Comment by spironato** [comment]
Thanks for the suggestion, i will think about it in the next weeks since at this point we must get rid of the use of `Reference`.  We need before upgrade to latest version.
