### ISSUE TITLE
Package is marked as unidentified in pub.dev

### ISSUE THREAD

**Issue by gmpassos** [petitparser/dart-petitparser#111]
For some reason the package have some building/analysis issues

https://pub.dev/packages/petitparser/score

**Comment by renggli** [comment]
Thank you for creating the issue. Unfortunately I cannot reproduce the problem locally (on the same code and with the version of Dart).

**Comment by gmpassos** [comment]
Are you using Dart 2.13.1?

**Comment by renggli** [comment]
Yes, see https://github.com/dart-lang/pub-dev/issues/4842.

**Comment by renggli** [comment]
Waiting for dart-lang/sdk#46183 to resolve.

**Comment by gmpassos** [comment]
I saw that they are using your package as reference.

**Comment by MrUnfunny** [comment]
@renggli the issue you linked has already been closed but this issue is still not resolved.

**Comment by renggli** [comment]
Not sure what i can do, release a new version with the same code? Or is there another way to rerun the analysis?

**Comment by renggli** [comment]
The problem resolved itself!

![ppgh](https://user-images.githubusercontent.com/131610/120884398-4b822300-c5e3-11eb-9e1a-1365c6db2bf5.png)
