### ISSUE TITLE
New Grammar Implementation Using PetitParser

### ISSUE THREAD

**Issue by Dokotela** [petitparser/dart-petitparser#115]
Hello!

Thanks so much for this package. I work with healthcare data, specifically that in the FHIR data standard (all json). It's official path language is called FHIRPath, and is defined using ANTLR. However, I found Petitparser much easier to work with. And have now beena ble to release the first dev version of FHIRPath for Dart! https://pub.dev/packages/fhir_path

**Comment by renggli** [comment]
Glad to hear and congrats on the first release!
