### ISSUE TITLE
The `word` parser should mention underscore `_`

### ISSUE THREAD

**Issue by gmpassos** [petitparser/dart-petitparser#116]
https://github.com/petitparser/dart-petitparser/blob/bada300011c0257e8789b0ec00cc1e5a16603340/petitparser/lib/src/parser/character/word.dart#L6

The `word` parser (`WordCharPredicate `) doesn't mention in the documentation or message that the underscore character is acceptable.

Reading the code we can see character `95` as one in the acceptable range.

Note that the common definition of a word only can start with a letter or a `_`, can't start with a digit. Need to document that too.

**Comment by renggli** [comment]
Thank you, thanks for reporting. Also the tutorial is misleading by implying that `letter() | digit()` is the same as `word()`.
