### ISSUE TITLE
How to upgrade?

### ISSUE THREAD

**Issue by SwiftyFlow** [petitparser/dart-petitparser#138]
petitparser   *4.4.0   *4.4.0      *4.4.0      5.0.0   

Not used by me but in .dart_tool...

**Comment by renggli** [comment]
Please provide a reproducible example. For dependencies to this package from other packages, please report a bug to the other package (there is nothing I can do here).

**Comment by SwiftyFlow** [comment]
No idea where it is, what it's for and why I have it...

![Screen Shot 2022-03-16 at 9 43 42 am](https://user-images.githubusercontent.com/5778905/158550902-7a3f806a-56df-4f4a-b8ce-ff5e17ebc2b9.png)

**Comment by renggli** [comment]
No idea why you have it either, I don't know your code 😄

**Comment by SwiftyFlow** [comment]
it's not my code it's in the dart.tool I didn't write that...

**Comment by renggli** [comment]
Then please report it to dart.tool.

**Comment by SwiftyFlow** [comment]
Will do. But anyway I'm here following a cascade of crap so I might just put the app in the bin

**Comment by SwiftyFlow** [comment]
Trying to upgrade because I couldn't install on android now it's also f***ed on iOS... 🤩🥳
