### ISSUE TITLE
Consider rolling meta back to ^1.8.0

### ISSUE THREAD

**Issue by jpeiffer** [petitparser/dart-petitparser#144]
The package `flutter_test` is pegged to `meta: 1.8.0`.  The dependency on `meta: ^1.9.0` means that any application that utilizes this package cannot easily utilize `flutter_test` when utilizing the latest `stable` version of Flutter, which is highly unfortunate for all Flutter applications.

If this depended on `^1.8.0` then internally it can use `^1.9.0` without breaking Flutter applications with unit tests.

**Comment by renggli** [comment]
From a practical standpoint I am unable to test with all possible old packages and SDK dependencies. New releases are always published with the latest stable dependencies. Consider sticking with an older version of this package until your dependencies have caught up.
