### ISSUE TITLE
Projects that are using PetitParser

### ISSUE THREAD

**Issue by II11II** [petitparser/dart-petitparser#157]
> Furthermore, there are [numerous open source projects](https://pub.dev/packages?q=dependency:petitparser) using PetitParser:

> ...
> [intl_translation](https://pub.dev/packages/intl_translation) provides internationalization and localization support to Dart.

Does intl_translation really use [dart-petitparser](https://github.com/petitparser/dart-petitparser) under the hood?

I could not find that intl_translation is dependent on dart-petitparser

**Comment by renggli** [comment]
Thanks for reporting, fixed in https://github.com/petitparser/dart-petitparser/commit/c6820c66cb46d9aadbef7a7be871739494cbaa8d.
