### ISSUE TITLE
Ignoring white-space

### ISSUE THREAD

**Issue by jonaskello** [petitparser/dart-petitparser#45]
What is the easiest way to globally ignore all white-space while parsing (without pre-processing the input to remove the white-space before parsing)?

**Comment by renggli** [comment]
Typically this is done by wrapping all your token with a white-space trimmer. For example, have a look at the JSON parser: https://github.com/petitparser/dart-petitparser/blob/master/lib/src/json/grammar.dart#L27.

**Comment by jonaskello** [comment]
Thanks, I'll have a look :-).
