### ISSUE TITLE
Duplicate library name throws Dart2JS compile warnings

### ISSUE THREAD

**Issue by tonyclickspace** [petitparser/dart-petitparser#56]
Compile warning:
`[Warning from Dart2JS on SlideSample|web/slide.dart]:
web/packages/petitparser/src/core/characters/optimize.dart:
Duplicated library name 'petitparser.core.characters.any_of'.
[Warning from Dart2JS on SlideSample|web/slide.dart]:
web/packages/petitparser/src/core/characters/any_of.dart:
Duplicated library name 'petitparser.core.characters.any_of'.`

**Comment by renggli** [comment]
Thank you for reporting. I hope to have fixed this with 77eac641725f47694f4a42aa5a396b5ad44e06a1. Unfortunately I am on holidays on a mobile phone only, so I could not thoroughly test the commit.
