### ISSUE TITLE
End of line check not working

### ISSUE THREAD

**Issue by Meai1** [petitparser/dart-petitparser#57]
I'm officially burned out now, why the heck is this not working?

```
var mtext = """use std\nuse blo""";
Parser bla =
// use
(whitespace().star().optional() & string("use") & whitespace().plus()
// [package name]
& word().plus().flatten()
// check for end of line
& whitespace().star().optional() & char("\n").plus()).times(2);
var res2 = bla.parse(mtext);
print(res2);
```

**Comment by renggli** [comment]
Two problems:

1. The `whitespace()` parser consumes newline characters, so it "eats" the "\n". Replace it with something more restrictive, for example a parser that only consumes spaces and tabs: `anyOf(" \t")`.
2. Your parser expect the input to end with a new-line, but your string does not. Have a look at [Parser#separatedBy()](https://github.com/petitparser/dart-petitparser/blob/ac23c03a614bf9553726db9cf10fd05e37f759f9/lib/src/core/parser.dart#L300), this might be the helper you are looking for.

Please ask further questions on StackOverflow. I am happy to help there.
