### ISSUE TITLE
trim().flatten() result value not trimmed

### ISSUE THREAD

**Issue by jackd** [petitparser/dart-petitparser#61]
Hi,
Firstly, awesome package! Bit scary at first, but examples are great. Greatly appreciate your work.

Minor issue I found:
```
print(char('x').trim().flatten().parse('x    ').value.length);  // 5
```
If I understand correctly, this should just match the `'x'` and discard trailing `whitespace`.  I had a look at the source code... but got scared again.

**Comment by renggli** [comment]
You need to swap the `trim()` and `flatten()` calls. `flatten` fattens everything that the inner parser consumes, so this includes the white-spaces that `trim` is consuming away.

    print(char('x').flatten().trim().parse('x    ').value.length);  // 1

**Comment by jackd** [comment]
Ah, I was thinking of it more as a `map` operation. Thanks again :).
