### ISSUE TITLE
Dart version

### ISSUE THREAD

**Issue by pradyukrish** [petitparser/dart-petitparser#66]
Hi @renggli , 

The version of Dart bundled with the latest version of flutter (1.2.1) is Dart 2.1.2.
I'm not able to use the latest version of  petitparser because it needs >= Dart 2.2.0. 
Can you please change the minimum required Dart version to 2.1.0?

Thanks

**Comment by renggli** [comment]
The problem is that the latest release of PetitParser depends on Dart 2.2. If you are using an older version of Dart you should depend on a compatible version, i.e. [PetitParser 2.1.1](https://pub.dartlang.org/packages/petitparser/versions/2.1.1).
