### ISSUE TITLE
Update README with some basic documentation on pattern().

### ISSUE THREAD

**Issue by wstrange** [petitparser/dart-petitparser#68]
It's not clear how pattern() works.

I am guessing that the the ^ symbol stands in for any valid character? Does that include unicode special characters? Umlauts, etc.

**Comment by renggli** [comment]
I agree, https://pub.dev/documentation/petitparser/latest/petitparser/pattern.html is not very explanatory. The string behaves like regular expression character classes. 

- `^` at the beginning inverts the pattern, and
- `a-z` includes the range of characters in the pattern, and
- any other character is added to the pattern verbatim (including unicode characters).

There are a bunch of examples in the tests: https://github.com/petitparser/dart-petitparser/blob/master/petitparser/test/petitparser_test.dart#L676

I'll try to transfer this information to the documentation with the next release.

**Comment by renggli** [comment]
Fixed with 25c8769155c9d69d2810d0dce6a47c3bd72f8cce.
