### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by rudolfolah** [petitparser/dart-petitparser#74]
Just wanted to say thanks for developing this library, very awesome that the API matches the version written for Smalltalk!

Also I knew there was something familiar about @renggli 's username...I wrote an article about using Magritte back in 2009 when I was taking a CS continuing education course: https://neverfriday.com/2009/04/13/how-i-used-magritte-seaside-smalltalk-for-cs-class-project/

Now I wonder; can Dart match some of the power of Smalltalk?

Thanks again for writing this library (and for Magritte!)

**Comment by renggli** [comment]
Thank you Rudolf for your compliments.

I like Dart. It is a great programming language that gets a lot of things right. You can see the influence of Smalltalk in many places. Lars Bak and Gilad Bracha obviously brought in their experience in the design.
