### ISSUE TITLE
Smalltalk parser seems to have some issues

### ISSUE THREAD

**Issue by xmehaut** [petitparser/dart-petitparser#78]
Hello,
I'm experimenting with the smalltalk parser, and I experienced issues with some configurations involving blocks as follows (dummy example): 
var source = '''exampleWithNumber: x
  |y z x|
  y := true & false not & (nil isNil) ifFalse: [self halt].
  self size + super size.
  #( #a "a" 1 1.0)
      do: [:each | Transcript show: (each class name);
                               show: ' '.].
   **x := y ifTrue:[x := 7] ifFalse:[8 essai].**
  ^ x < y'''
the parser doesn't seems to paser th bold line.
But if I write this, its works : 
var source = '''exampleWithNumber: x
  |y z x|
  y := true & false not & (nil isNil) ifFalse: [self halt].
  self size + super size.
  #( #a "a" 1 1.0)
      do: [:each | Transcript show: (each class name);
                               show: ' '.].
   **(**x := 5 ifTrue:[x := 7] ifFalse:[8 essai]**).**
  ^ x < y'''

any clues?

**Comment by renggli** [comment]
Thank you for reporting. Does not seem to have to do with blocks, but assignments. Minimal example I could come up with is the following:

```smalltalk
example
  super example.
  x := y negate
```

**Comment by xmehaut** [comment]
Thank for your answer ; it fails also for me.
Weird :-(
I've tried several changes in the grammar, but not yet found the error.

Le lun. 25 mai 2020 à 13:31, Lukas Renggli <notifications@github.com> a
écrit :

**Comment by renggli** [comment]
I've exported this grammar from Pharo Smalltalk and migrated the unit tests, but other than that it has not seen any use. In Pharo the same grammar was used to successfully parse and recompile the complete image; but maybe something got lost when exporting. Unfortunately I can't run my old images anymore, will have a look later tonight if I can spot an obvious problem.

**Comment by xmehaut** [comment]
Thanks a lot ; I've personally the Cincom image and the parser is quite
different.

Le lun. 25 mai 2020 à 13:58, Lukas Renggli <notifications@github.com> a
écrit :

**Comment by xmehaut** [comment]
Thanks renggli ; it was indeed subtile (i don't understand the impact  :-() ..

moreover, when i look at the equivalent parser in https://github.com/moosetechnology/PetitParser/blob/development/src/PetitSmalltalk/PPSmalltalkGrammar.class.st, I've some changes from the dart one...

best regards

**Comment by renggli** [comment]
The Dart code was auto-exported from Smalltalk over 7 years ago with this commit: 3a424af29bb8a2bd782dfb824ad485a000abbf83. I have not touched the grammar since, other than to make it work with the latest version of PetitParser in Dart (migrate to using the grammar definition builder). Also I have not touched the original Smalltalk code in over 10 years, so I don't know if any changes were made on the Smalltalk side?

**Comment by xmehaut** [comment]
Nevertheless thanks for the correction. How did you find the bug?

Envoyé de mon iPhone

**Comment by renggli** [comment]
I looked at the [parse trace](https://github.com/petitparser/dart-petitparser/blob/master/petitparser/lib/src/debug/trace.dart) of the two inputs. There I saw that the statement separating dot was consumed as a binary selector token.

**Comment by xmehaut** [comment]
Ah thx! Nice to have a trace ; it will be easier :)

Envoyé de mon iPhone
