### ISSUE TITLE
Support tracing across reference boundaries

### ISSUE THREAD

**Issue by shyndman** [petitparser/dart-petitparser#86]
Hi there,

I noticed that `trace` parsers are unable to trace the "children" of `Reference` parsers, which would be handy.

I got around this without too much trouble (little code change, and introduced the trace in the referenced function), but it would be really nice to see a cohesive trace through the entirety of the input, with proper indentation and all that.

Anyway, thanks! This library has proven useful for a tiny DSL I'm writing.

**Comment by shyndman** [comment]
Ah, I see now why this is a little tricky. Hmmm

**Comment by renggli** [comment]
Reference boundaries disappear when the parser is built, I don't see how they would affect the trace? Can you provide an example?

**Comment by shyndman** [comment]
So right now I'm applying the trace inside my `GrammarDefinition`...should I be wrapping my `GrammarParser` instance in the trace instead?

**Comment by shyndman** [comment]
Yes. That worked perfectly. Thank you.

**Comment by renggli** [comment]
Yeah, it does not work inside the `GrammarDefinition`, it only works after the parser is built. Similar issue as #39.
