### ISSUE TITLE
Parser isn't const anymore [4.0.0-nullsafety]

### ISSUE THREAD

**Issue by modulovalue** [petitparser/dart-petitparser#88]
See https://github.com/petitparser/dart-petitparser/blob/f31e6c616613ed3ef32aedd75a2cbc2ac8871e79/petitparser/lib/src/core/parser.dart#L11

Unless I'm missing something, this was, could and should be a const constructor so that subclasses can also be const.

**Comment by renggli** [comment]
I intentionally removed it with 4.0.0 because the null-safety changes brought various breaking changes anyway. The const-ness was only used by `PositionParser` and it caused more complications than it solved. I missed to document it in CHANGES.md; will add that right away.

Is there a particular reason you needed const parsers?

**Comment by modulovalue** [comment]
I'm using more strictly typed parsers such as 

```dart
class FMap2LocParser<A, B, R> extends Parser<R> {
  final Parser<A> a;
  final Parser<B> b;
  final R Function(A, B, Loc) fn;

  /*const*/ FMap2LocParser(this.a, this.b, this.fn);

  @override
  Result<R> parseOn(Context context) {
    final resultA = a.parseOn(context);
    if (resultA.isFailure) {
      return resultA.failure(resultA.message);
    } else {
      final resultB = b.parseOn(resultA);
      if (resultB.isFailure) {
        return resultB.failure(resultB.message);
      } else {
        return resultB.success(fn(
          resultA.value,
          resultB.value,
          ParserLocation(resultB.value, context.position, resultB.position),
        ));
      }
    }
  }

  @override
  FMap2LocParser<A, B, R> copy() => FMap2LocParser(a, b, fn);
}
```

The reason for it being const is, if fn were to be a top-level function and a and b const, the whole Parser could be const which would have a positive impact on memory (and potentially performance).

> and it caused more complications than it solved

Could you elaborate on the complications that it caused?

**Comment by renggli** [comment]
The spacial cases were in the testing infrastructure and the equality testing in the transformation library; what caused the confusion to users though was that depending on the setting of you analyzer it would suggest for some parsers to use const while for others not.

**Comment by modulovalue** [comment]
> it would suggest for some parsers to use const while for others not.

I don’t believe this should be seen as a bad thing. Those that don’t want that to happen should disable the prefer_const(_constructors) lint, if that‘s the one that you are referring to.

If that’s not possible, then there are other ways to disable that behavior such as wrapping the parser in a function or removing the const keyword from the subclassing parsers constructor. Have you considered these options?

**Comment by renggli** [comment]
As I wrote, I don't think it is worth the troubles to have const-ness at the root of the parser hierarchy that is mutable for the 35+ of its core-subclasses. 

Also note that your example parser puzzles me: for example, you create identical duplicated instances in the copy method (something you say you want to avoid); and your parsers are broken with regard to the transformation API (missing implementation of `children` and `replace`) that is needed when resolving circular dependencies in a `GrammarDefinition`.

**Comment by modulovalue** [comment]
<img width="1489" alt="Bildschirmfoto 2020-11-19 um 15 20 31" src="https://user-images.githubusercontent.com/24444584/99678734-6f34b000-2a7b-11eb-9fed-ec3dc501953e.png">

I have modelled my helper parsers after the parsers on the top right side of the petitparser class hierarchy in the image above (e.g. CharacterParser). They all have no state and could be made const for potential memory optimizations if the consumers were to use the const 'facilities' provided by dart.

The mutating state seems to be exclusive to DelegateParser and its subclasses. Since DelegateParser seems to be the only superclass for mutating parsers, making DelegateParser non-const, would guard all its subclasses from being const.




> that is needed when resolving circular dependencies

I resolve circular dependencies statically by explicitly modelling the parser graph in a way that makes circular dependencies obvious through analyzer-assisted forced forward declarations to then wrap them in a reference.


I mostly just wanted to use const parsers for future optimizations. If you disagree about making Parser const againg, that's fine with me. (I'm aware that I'm not entirely using petitparser the way that it was designed to be used.)
