### ISSUE TITLE
Best way to report parse failures

### ISSUE THREAD

**Issue by gtnicol** [petitparser/dart-petitparser#98]
I have a pretty complex parser, and in the test cases, I sometimes get exceptions like the following. 

```
==>endDocument expected 87
Failure[4:1]: endDocument expected
```

I'd like to provide details, like line number, offset, and a context string to make it easy to debug and also to help when people are creating data to be parsed. Going through Failure etc. and I can't see an easy way to do this. This might be just a documentation update, but what's the best approach for this?

**Comment by renggli** [comment]
The [Failure](https://pub.dev/documentation/petitparser/latest/context/Failure-class.html) contains information about the error, such as the `position` in the input buffer, the line and column (`4:1` in your output), etc.

Error messages are auto-generated by default; but all messaging can be customized through optional arguments in the respective constructor methods. Most common is with [Parser.flatten](https://pub.dev/documentation/petitparser/latest/parser/FlattenParserExtension/flatten.html).

Another way to further customize the error reporting is to wrap a graph of parsers with a choice of the parser and an always failing one: `myParser.or(failure('unable to parse myParser ...'))`. This will replace an error reported within `myParser` with a more readable custom error message.

There are numerous examples in this an other repositories:
- https://github.com/petitparser/dart-petitparser/blob/c225ac2effc39fa6d6d9d57706008aa9e6b09aec/petitparser_examples/lib/src/lisp/grammar.dart#L31
- https://github.com/renggli/dart-xml/blob/a57883b91c340d7042cc1417eb3b2cc0f91b4cfc/lib/src/xml/production.dart#L33

**Comment by gtnicol** [comment]
Thanks. In the JSON parser, I see a string grammar, which is basically the same as I am using. The error above is coming when a malformed string is found (like `foo="bar"bar"quiz"` - i.e. the string literal on a name/value pair), and always gives the same error because the parser is unable to match the outer expression and is reporting the error at that location. Is there a way to show the stack trace (i.e. the production that failed) in the error message?

**Comment by renggli** [comment]
Not sure I understand, could you provide a runnable minimal example? Alternatively a couple of test-cases for the JSON parser could maybe help too?

**Comment by gtnicol** [comment]
If you run the following the error shows `Failure[1:1]: Expected null`... minimally it would be good to indicate which line had an error.
```
  test('json', () {
    const String invalid = '''
{
   "a": 1,
   "b": 2,
   "c": 3,
   "d": 4,
   "e": 5,
   "f": 6,
   "g": "bad "value" string",
}
''';
    final JsonParser json = JsonParser();
    var result = json.parse(invalid);
    print(result);
  });
```

**Comment by renggli** [comment]
The error you observe boils down to the order in which the `value` production parses its children and that the ordered choice always reports on the last error; which in this case is arguably not very nice. For example, if you move `ref(object)` last in the choice (or add it a second time), you get a much better error `Failure[8:15]: Expected }`.

That said, I've been experimenting with providing better error reporting on ordered choices in the past (also I am reading that this is an open research topic, i.e. https://arxiv.org/abs/1405.6646). The reason I've never committed anything to the core framework is that it adds some overhead and the examples I had disappeared again. Let's reuse this bug to track this.

**Comment by renggli** [comment]
I've backported the old [choice-failures](https://github.com/petitparser/dart-petitparser/tree/choice-failures) branch into a new [choice-strategy](https://github.com/petitparser/dart-petitparser/tree/choice-strategy). Though this comes at a price, it makes the average parser 10% slower ...

**Comment by gtnicol** [comment]
Thanks for the quick response. I'll pull the branch and play around. Error reporting in parsers is notoriously difficult. Years ago I wrote a recursive descent parser generator which had similar kinds of issues and I ended up adding a stack to the context to track the last parse, but it still wasn't that great.
